[config]
[server]
port = 8083
workers = 4
kafka_workers = 3
log_level = 'debug'
redis_connection_string = 'redis://172.17.0.4:6379'

[kafka_producer]
bootstrap_servers = '172.17.0.3:9092'
message_timeout_ms = '5000'

[kafka_consumer]
group_id = '2'
bootstrap_servers = '172.17.0.3:9092'
enable_partition_eof = 'false'
session_timeout_ms = '6000'
enable_auto_commit = 'false'

[kafka_topics]
warehouse_service_topic = 'warehouse'
transactions_topic = 'transactions'
