apiVersion: apps/v1  # API version
kind: Deployment
metadata:
  name: warehouse    # Unique name for the deployment
  labels:
    app: warehouse   # Labels to be applied to this deployment
spec:
  selector:
    matchLabels:     # This deployment applies to the Pods matching these labels
      app: warehouse
  replicas: 1        # Run a single pod in the deployment
  template:          # Template for the pods that will be created by this deployment
    metadata:
      labels:        # Labels to be applied to the Pods in this deployment
        app: warehouse
    spec:            # Spec for the container which will be run inside the Pod.
      containers:
      - name: warehouse
        image: lieroz/warehouse
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8083

---        
apiVersion: v1
kind: Service        # Type of Kubernetes resource
metadata:
  name: warehouse    # Name of the Kubernetes resource
  labels:            # Labels that will be applied to this resource
    app: warehouse
spec:
  ports:
  - port: 8083       # Map incoming connections on port 6379 to the target port 6379 of the Pod
    targetPort: 8083
  selector:          # Map any Pod with the specified labels to this service
    app: warehouse
