[config]
[server]
port = 8080
workers = 4
log_level = 'debug'

[kafka_producer]
brokers = 'localhost:9092'
message_timeout = '5000'

[kafka_topics]
orders_service_topic = 'orders'
billing_service_topic = 'billings'

[services]
orders_service_addr = 'localhost:8081'
warehouse_service_addr = 'localhost:8083'
