[config]
[server]
port = 8080
workers = 4
log_level = 'debug'
redis_connection_string = 'redis://host.docker.internal:6379'

[kafka_producer]
bootstrap_servers = 'host.docker.internal:9092'
message_timeout_ms = '5000'

[kafka_topics]
orders_service_topic = 'orders'
billing_service_topic = 'billings'

[services]
orders_service_addr = 'orders:8081'
warehouse_service_addr = 'warehouse:8083'
